name: "Setup and build"
description: "Setup and build"
runs:
  using: "composite"
  steps:
    - name: Install node
      uses: actions/setup-node@v4
      with:
        node-version-file: ".nvmrc"

    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    # Not having this will break the windows build because the PATH won't be set by msbuild.
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
      if: runner.os == 'Windows'

    - name: Download latest antd core bins windows
      shell: bash
      if: runner.os == 'Windows'
      run: ./tools/download-antd-files.sh https://github.com/antd-io/antd-core/releases/download/v11.4.0/antd-win-x64-11.4.0.zip

    - name: Download latest antd core bins macos
      shell: bash
      if: runner.os == 'macOS'
      run: ./tools/download-antd-files.sh https://github.com/antd-io/antd-core/releases/download/v11.4.0/antd-macos-x86_64-11.4.0.tar.xz

    - name: Download latest antd core bins linux
      shell: bash
      if: runner.os == 'Linux'
      run: ./tools/download-antd-files.sh https://github.com/antd-io/antd-core/releases/download/v11.4.0/antd-linux-x86_64-11.4.0.tar.xz

    - name: Install dependencies
      shell: bash
      run: npm ci
